### ISSUE TITLE
Postgres lib update

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1667]
Currently, I am using Mainflux 0.12.1, Some service Mainflux when connect to the Postgres database (Through Haproxy). When I try some requests to Platform, it's fine.
![image](https://user-images.githubusercontent.com/35691187/202075485-b72eaa30-3c0d-4ecb-9f56-10ad96ce2d45.png)
But sometimes, the request is fail. Here is image of error.
![image](https://user-images.githubusercontent.com/35691187/202075322-1416563b-ac0c-4bc6-8694-3c82ee4f0342.png).

I wonder it's a bug of platform or related to database?

look like this issue: https://blog.bossylobster.com/2020/12/broken-pipe.html (Golang lib). It said: "it a bug of lib/pq"? anything update?

**Comment by ChiQuang98** [comment]
I am going close this issue, I think it causes by a timeout connection Postgres

**Comment by chombium** [comment]
Hi @ChiQuang98,

Have you checked the haproxy logs if there is something interesting there?

**Comment by ChiQuang98** [comment]
I think if mainflux connects to Postgres through Haproxy, sometime it will break the connection cause of the Timeout connection Haproxy. you guys don't meet that error because you have just tested when mainflux connected to Postgres directly. In my opinion, Have you used any retry connection to the Database when the connection is broken (before throwing any response error to the user).

**Comment by chombium** [comment]
Hi @ChiQuang98,

thank you very much for the clarification.

We should check which part of the connection breaks due to idle connections:
- Mainflux service -> haproxy
- haproxy -> PostgreSQL database

I'll check how do we configure the connections to the the database and check what's happening in the connection. From what I found so far it seems that for the connection from the Mainflux service to haproxy, the Go pg sql driver has a [keep alive](cf.announce@listserv.sap.corp) by default.

I suspect that there should be something in the configuration of haproxy which should be set to take the keep-alive into account. I will check that and what is needed to keep the connection from haproxy to the db server alive.

Can you please share some details about how you've done your setup? How have you deployed and configured haproxy? This would help me to reproduce the issue

**Comment by ChiQuang98** [comment]
Here is the conf Haproxy That I am using:
![image](https://user-images.githubusercontent.com/35691187/206433610-1f8ce8c5-7d10-4c5f-9183-f5e1bc59cb41.png)
I set timeout up to 10 hours, But I think if there is no action in 10 hours, the first request after 10 hours will fail, and the second request will succeed (Because the broken pipe has been fixed after the first request). My other services, which connect to Postgres through HaProxy, are working fine.

**Comment by dborovcanin** [comment]
We have tested the connection to the DB in the Docker environment. If DB container is stopped or removed, service (Users, in particular) fails, but when DB container is recreated, Postgres lib takes care of reconnection and everything seems to be working fine.

**Comment by ChiQuang98** [comment]
Yep, in that case, everything will be fine. Even when Mainflux services connect to Postgres through Haproxy is fine too. But what about when there has been no action in a long time? some broken pipe will happen.

**Comment by dborovcanin** [comment]
I'll try and test with some long timeouts locally, but that's still not the exact environment to reproduce the issue. If you deployed on k8s, did you consider using some kind of liveness or readiness probe from the service pod?

**Comment by ChiQuang98** [comment]
I deployed on k8s, And testing both connect to DB directly and through HAproxy, The issue happens when connecting through Haproxy. I will take a look at " the liveness or readiness probe from the service pod". The last issue to make my project is production :(. If I can not fix it, I have to connect to DB directly. And reconfig to another destination IP if the master DB postgres is down. (HAProxy helps us don't need to change the IP if the master DB is down)

**Comment by dborovcanin** [comment]
Unfortunately, I think we can't do much, but I think that [liveness/readiness in k8s](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) will help you. Let's keep this issue open so someone from the community can help you, and so you can leave a comment when you solve the problem. We can also improve our Helm charts if this approach helps you.

**Comment by ChiQuang98** [comment]
Hi again, @dborovcanin . You guys have used this version of lib? https://github.com/lib/pq/issues/870. This issue is related to the issue that I have mentioned before.

**Comment by dborovcanin** [comment]
Hello, @ChiQuang98. Which version exactly? We have been updating our dependencies regularly, and it looks like this bug has been resolved over 3y ago. Which version of Mainflux are you using? Either way, it's a good point that we should switch to `sqlx`, we have already done it on some other projects.

**Comment by dborovcanin** [comment]
@ChiQuang98 I have sent a PR to change the underlying lib, that's something we should do as per the original lib recommendation anyway. If we accept that PR, you can try with the latest version and let us know if the issue is resolved.

**Comment by ChiQuang98** [comment]
Hi, I am using mainflux 0.12.1. Should I update to latest version?

**Comment by dborovcanin** [comment]
That's a very old version. TBH, some significant changes are coming to Mainflux, so I'm not sure if it's worth updating to 0.13 at the moment. It'll probably be best to wait for 0.14 and resolve the issue using k8s, since a probe should be in place regardless of the code updates. The readiness probe is more resilient to deployment changes.

**Comment by ChiQuang98** [comment]
Hmm, I will try with mainflux 0.13. Hopefully all of api don’t change

**Comment by dborovcanin** [comment]
In that case, you can even try with the latest, since these changes will be added to it as soon as we merge the PR.

**Comment by dborovcanin** [comment]
@ChiQuang98 Any updates on this one? If not, I'll close soon due to inactivity.

**Comment by dborovcanin** [comment]
Closing due to inactivity.
